### ISSUE TITLE
高德地图不显示

### ISSUE THREAD

**Issue by sauchye** [adad184/DemoNavigationURI#1]
iOS 9，安装了高德地图，但是高德地图不能被检测出来，只显示了苹果地图。

**Comment by adad184** [comment]
请问iOS版本是多少?  高德地图的版本是多少?

**Comment by sauchye** [comment]
iOS 9 Beta 3还是4来着，高德地图v7.3.6.2017

**Comment by adad184** [comment]
噢  这是因为iOS9对openURL做了进一步的限制 需要在plist中添加url scheme白名单才行 稍后我会更新一下文章和代码

**Comment by adad184** [comment]
@sauchye 已更新 请重新验证一下

**Comment by sauchye** [comment]
@adad184  非常完美，弱弱的问下，您只是配置了plist文件了。

**Comment by adad184** [comment]
是的  :)

**Comment by sauchye** [comment]
灰常感谢
